# Generated by Django 4.0.4 on 2022-04-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0002_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
