# Generated by Django 4.0.4 on 2022-04-30 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='detail',
            field=models.TextField(default='Please add detail instructions'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serving',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Recipe_Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipe_app.Recipe_Ingredient', to='recipe_app.ingredient'),
        ),
    ]
