# Generated by Django 4.0.4 on 2022-05-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_recipe_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='serving',
            new_name='servings',
        ),
    ]
