# Generated by Django 4.0.4 on 2022-05-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_rename_serving_recipe_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='des',
            field=models.TextField(max_length=100),
        ),
    ]
