# Generated by Django 4.0.4 on 2022-05-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0007_alter_recipe_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='des',
            field=models.TextField(),
        ),
    ]
